[project]
name = "llm-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "langchain>=0.3.27",
    "langgraph>=0.6.7",
    "pydantic-settings>=2.11.0",
    "uvicorn[standard]>=0.37.0",
]
